### ISSUE TITLE
Could you please tell me the commands step by step to run your model? Thank you!

### ISSUE THREAD

**Issue by yyyhz** [NJUNLP/MAPO#1]

**Comment by Ricardokevins** [comment]
> _No description provided._

Hi, I thnk the process should be as followed:

1. pip install -r requirement.txt to install the env.
2. Choose a model you like to download from here: [MAPO-collection](https://huggingface.co/collections/kevinpro/mapo-multilingual-reasoning-with-preference-optimization-65e975342dcdb39d19646a6c)
3. Step into Evaluation and run the script file: run.sh (model path should be set correctly)

If you have any question, feel free to raise the issue.

**Comment by yyyhz** [comment]
> > _No description provided. 未提供说明。_
> 
> Hi, I thnk the process should be as followed:嗨，我该过程应如下：
> 
> 1. pip install -r requirement.txt to install the env.pip install -r requirement.txt安装环境。
> 2. Choose a model you like to download from here: [MAPO-collection](https://huggingface.co/collections/kevinpro/mapo-multilingual-reasoning-with-preference-optimization-65e975342dcdb39d19646a6c)从这里选择您喜欢下载的模型：MAPO-collection
> 3. Step into Evaluation and run the script file: run.sh (model path should be set correctly)单步执行评估并运行脚本文件：run.sh（模型路径应正确设置）
> 
> If you have any question, feel free to raise the issue.如果您有任何问题，请随时提出问题。

Thank you for your reply! 
But I would like to reproduce your code, e.g. step-by-step from MathOctopus to MathOctopus-MAPO. 
In the reproduction process, there may be some models missing (including but not limited to /mnt/data/shesj/PLM/nllb-200-distilled-600M, etc) as well as more difficult to modify code(including but not limited to No module named 'utils.generatePrompt'). not sure. I would be appreciated if you can focus on this.

**Comment by Ricardokevins** [comment]
> > > _No description provided. 未提供说明。_
> > 
> > 
> > Hi, I thnk the process should be as followed:嗨，我该过程应如下：
> > 
> > 1. pip install -r requirement.txt to install the env.pip install -r requirement.txt安装环境。
> > 2. Choose a model you like to download from here: [MAPO-collection](https://huggingface.co/collections/kevinpro/mapo-multilingual-reasoning-with-preference-optimization-65e975342dcdb39d19646a6c)从这里选择您喜欢下载的模型：MAPO-collection
> > 3. Step into Evaluation and run the script file: run.sh (model path should be set correctly)单步执行评估并运行脚本文件：run.sh（模型路径应正确设置）
> > 
> > If you have any question, feel free to raise the issue.如果您有任何问题，请随时提出问题。
> 
> Thank you for your reply! But I would like to reproduce your code, e.g. step-by-step from MathOctopus to MathOctopus-MAPO. In the reproduction process, there may be some models missing (including but not limited to /mnt/data/shesj/PLM/nllb-200-distilled-600M, etc) as well as more difficult to modify code(including but not limited to No module named 'utils.generatePrompt'). not sure. I would be appreciated if you can focus on this.

Thank you for your suggestion! I am working on providing a more detailed instructions

**Comment by yyyhz** [comment]
> > > > _No description provided. 未提供说明。未提供说明。未提供说明。_
> > > 
> > > 
> > > Hi, I thnk the process should be as followed:嗨，我该过程应如下：嗨，我该过程应如下：嗨，我该过程应如下：
> > > 
> > > 1. pip install -r requirement.txt to install the env.pip install -r requirement.txt安装环境。pip install -r requirement.txt安装 env.pip install -r requirement.txt安装环境。
> > > 2. Choose a model you like to download from here: [MAPO-collection](https://huggingface.co/collections/kevinpro/mapo-multilingual-reasoning-with-preference-optimization-65e975342dcdb39d19646a6c)从这里选择您喜欢下载的模型：MAPO-collection从这里选择您喜欢下载的模型： MAPO-collection从这里选择您喜欢下载的模型：MAPO-collection
> > > 3. Step into Evaluation and run the script file: run.sh (model path should be set correctly)单步执行评估并运行脚本文件：run.sh（模型路径应正确设置）
> > > 
> > > If you have any question, feel free to raise the issue.如果您有任何问题，请随时提出问题。
> > 
> > 
> > Thank you for your reply! But I would like to reproduce your code, e.g. step-by-step from MathOctopus to MathOctopus-MAPO. In the reproduction process, there may be some models missing (including but not limited to /mnt/data/shesj/PLM/nllb-200-distilled-600M, etc) as well as more difficult to modify code(including but not limited to No module named 'utils.generatePrompt'). not sure. I would be appreciated if you can focus on this.感谢您的回复！但我想重现您的代码，例如从MathOctopus逐步到MathOctopus-MAPO。在复制过程中，可能会缺少一些模型（包括但不限于 /mnt/data/shesj/PLM/nllb-200-distilled-600M 等）以及更难修改的代码（包括但不限于 No module named 'utils.generatePrompt'）。不确定。如果您能专注于此，我将不胜感激。
> 
> Thank you for your suggestion! I am working on providing a more detailed instructions谢谢你的建议！我正在努力提供更详细的说明

And I have a more **urgent** question, I didn't find your open source utils.py file. This is a **very urgent issue** for me and I would appreciate it if you could open source it!
 No module named 'utils.generatePrompt'

**Comment by Ricardokevins** [comment]
I have tried to fix the problem

You can pull the latest code and try again

**Comment by yyyhz** [comment]
> I have tried to fix the problem我已尝试解决问题
> 
> You can pull the latest code and try again您可以提取最新代码，然后重试

Thanks for the update!
If it's possible, could you please provide the contents of your mnt (e.g. /mnt/data/shesj/PLM/nllb-200-distilled-600M, /mnt/data/shesj/RL4CoT, etc.)

**Comment by Ricardokevins** [comment]
> > I have tried to fix the problem我已尝试解决问题
> > You can pull the latest code and try again您可以提取最新代码，然后重试
> 
> Thanks for the update! If it's possible, could you please provide the contents of your mnt (e.g. /mnt/data/shesj/PLM/nllb-200-distilled-600M, /mnt/data/shesj/RL4CoT, etc.)


The original path for my algorithm development, /mnt/data/shesj/RL4CoT, contains a large number of disorganized files. The code in the repository has been refactored and reorganized.

nllb-200-distilled-600M is a public translation model, you can download it from huggingface and you can also refer to the paper for more details.

**Comment by yyyhz** [comment]
> > > I have tried to fix the problem我已尝试解决问题
> > > You can pull the latest code and try again您可以提取最新代码，然后重试
> > 
> > 
> > Thanks for the update! If it's possible, could you please provide the contents of your mnt (e.g. /mnt/data/shesj/PLM/nllb-200-distilled-600M, /mnt/data/shesj/RL4CoT, etc.)
> 
> The original path for my algorithm development, /mnt/data/shesj/RL4CoT, contains a large number of disorganized files. The code in the repository has been refactored and reorganized.
> 
> nllb-200-distilled-600M is a public translation model, you can download it from huggingface and you can also refer to the paper for more details.

![微信图片_20240613150400](https://github.com/NJUNLP/MAPO/assets/92558414/9dc5855b-32c4-423e-94bc-385b4af6adf9)
I have used your lastest code, it is work for me! 
But I have new problem when I try to run ppo.py.

**Comment by yyyhz** [comment]
> > > I have tried to fix the problem我已尝试解决问题
> > > You can pull the latest code and try again您可以提取最新代码，然后重试
> > 
> > 
> > Thanks for the update! If it's possible, could you please provide the contents of your mnt (e.g. /mnt/data/shesj/PLM/nllb-200-distilled-600M, /mnt/data/shesj/RL4CoT, etc.)
> 
> The original path for my algorithm development, /mnt/data/shesj/RL4CoT, contains a large number of disorganized files. The code in the repository has been refactored and reorganized.
> 
> nllb-200-distilled-600M is a public translation model, you can download it from huggingface and you can also refer to the paper for more details.

I have used your lastest code, it is work for me! 
1. But I have **new problem** when I try to run **ppo.py**. Change the _model_ in **ppo_trainer** to _model.critic_model_ and there will be no error. But I don't know if that's correct.
2. And also I am not sure where is the **explore_data** in this PPO config file comes from, the readme doesn't show.
![微信图片_20240613150400](https://github.com/NJUNLP/MAPO/assets/92558414/538e49ce-1000-4617-a52b-25fba56a7fd8)
![微信图片_20240613152705](https://github.com/NJUNLP/MAPO/assets/92558414/aa12895f-ebfd-4a82-a89a-2f6b5f37ecd3)

**Comment by Ricardokevins** [comment]
> > > > I have tried to fix the problem我已尝试解决问题
> > > > You can pull the latest code and try again您可以提取最新代码，然后重试
> > > 
> > > 
> > > Thanks for the update! If it's possible, could you please provide the contents of your mnt (e.g. /mnt/data/shesj/PLM/nllb-200-distilled-600M, /mnt/data/shesj/RL4CoT, etc.)
> > 
> > 
> > The original path for my algorithm development, /mnt/data/shesj/RL4CoT, contains a large number of disorganized files. The code in the repository has been refactored and reorganized.
> > nllb-200-distilled-600M is a public translation model, you can download it from huggingface and you can also refer to the paper for more details.
> 
> I have used your lastest code, it is work for me!
> 
> 1. But I have **new problem** when I try to run **ppo.py**. Change the _model_ in **ppo_trainer** to _model.critic_model_ and there will be no error. But I don't know if that's correct.
> 2. And also I am not sure where is the **explore_data** in this PPO config file comes from, the readme doesn't show.
>    ![微信图片_20240613150400](https://private-user-images.githubusercontent.com/92558414/339258759-538e49ce-1000-4617-a52b-25fba56a7fd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NzQxNDEsIm5iZiI6MTcxODQ3Mzg0MSwicGF0aCI6Ii85MjU1ODQxNC8zMzkyNTg3NTktNTM4ZTQ5Y2UtMTAwMC00NjE3LWE1MmItMjVmYmE1NmE3ZmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDE3NTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYWYxYjk4ZGM4OTdlY2I3NTlhNzViZGU4OWQ4NzFiZDA0ZWI5NzRhYzZiMGEwYTU2NmIxNDVmYWIyNzE4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X2BEIGumQnNbMU0HhOyTn_JgAkQIqkzTleS86eWT0X4)
>    ![微信图片_20240613152705](https://private-user-images.githubusercontent.com/92558414/339258836-aa12895f-ebfd-4a82-a89a-2f6b5f37ecd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NzQxNDEsIm5iZiI6MTcxODQ3Mzg0MSwicGF0aCI6Ii85MjU1ODQxNC8zMzkyNTg4MzYtYWExMjg5NWYtZWJmZC00YTgyLWE4OWEtMmY2YjVmMzdlY2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDE3NTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NGZmZDFhZjVjNzQ1NGZhNzU0ZGJkMzZhMzMwN2IzMTQwYTIxMWM3Y2YyN2FlMGZlODFmNTIwYzFkZWFmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pzzqOUm2kQ6XHckf53wku_HpW26O1dSChu9PI4NxA24)


Due to changes in the working environment, there might be some inconsistency in some file names. I have made many effort to locate the previous data files, and you can refer to the files in the following link for use.

https://github.com/NJUNLP/MAPO/blob/main/Data/numglue-mutli-lingual_NoEnglishForPPO.json
