### ISSUE TITLE
DPO degeneration problem

### ISSUE THREAD

**Issue by WJMacro** [NJUNLP/MAPO#3]
Hello! Thank you for your work; I have some technical issues I'd like to discuss with you. 
I noticed that you mentioned encountering a problem where the model repeatedly generated the same token after DPO training. We are experiencing a similar issue in our current experiments. Could you share how you resolved this issue?

**Comment by Ricardokevins** [comment]
> Hello! Thank you for your work; I have some technical issues I'd like to discuss with you. I noticed that you mentioned encountering a problem where the model repeatedly generated the same token after DPO training. We are experiencing a similar issue in our current experiments. Could you share how you resolved this issue?

1. You can put those bad sampling output with repetition to "Reject" to penalize this behavior
2. You can also try to lower the learning rate

And recently, I also try to mix dpo-loss and sft-loss, which may help to get a stable training reuslt
